name: Broadcast
main: uk.co.jordanmcqueen.Broadcast.Broadcast
version: 1.1
description: >
             Broadcasts messages at a set interval.
commands:
  stopbroadcast:
    description: Prevents the broadcasting from continuing.
  startbroadcast:
    description: Initiates the broadcasting process.
