name: Broadcast
main: uk.co.jordanmcqueen.Broadcast.Broadcast
version: 2.1
description: >
             Broadcasts messages at a set interval.
commands:
  reloadbroadcast:
    description: Reloads the plugin (Needs broadcast.reload or OP)
